#!/usr/bin/env python3
"""Genera Procesamiento_Datos_Campo_v1.ipynb"""
import json

def cc(cid, lines):
    return {"cell_type":"code","execution_count":None,"id":cid,
            "metadata":{},"outputs":[],"source":lines}
def mc(cid, lines):
    return {"cell_type":"markdown","id":cid,"metadata":{},"source":lines}

# =============================================================================
# CONTENIDO DE CADA CELDA (lista de strings, una por línea de código)
# =============================================================================

IMPORTS_SRC = [
    "import os\n",
    "import time\n",
    "import glob\n",
    "import traceback\n",
    "import gc\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from multiprocessing import Pool\n",
    "from functools import partial\n",
    "import ROOT\n",
    "\n",
    "# kError silencia los TStreamerInfo warnings que aparecen al leer\n",
    "# archivos .root generados con versiones distintas de Offline.\n",
    "# En el notebook de prueba usábamos kWarning; acá subimos el umbral\n",
    "# para no saturar la salida cuando corren 8 workers en paralelo.\n",
    "ROOT.gROOT.SetBatch(True)\n",
    "ROOT.gErrorIgnoreLevel = ROOT.kError\n",
    "\n",
    "print('Imports OK')",
]

AUGER_SRC = [
    "AugerOfflineRoot = os.environ.get('AUGEROFFLINEROOT')\n",
    "if AugerOfflineRoot is None:\n",
    "    raise EnvironmentError(\n",
    "        'AUGEROFFLINEROOT no definido.\\n'\n",
    "        'Correr Jupyter desde una terminal donde se haya hecho:\\n'\n",
    "        '  aug_set_version offline 4.0.1-icrc23-prod1-root6\\n'\n",
    "        '  source .../bin/this-auger-offline.sh'\n",
    "    )\n",
    "print(f'AUGEROFFLINEROOT: {AugerOfflineRoot}')\n",
    "\n",
    "for lib in ['libRecEventKG.so']:\n",
    "    lib_path = os.path.join(AugerOfflineRoot, 'lib', lib)\n",
    "    if not os.path.exists(lib_path):\n",
    "        raise FileNotFoundError(f'No se encontro: {lib_path}')\n",
    "    status = ROOT.gSystem.Load(lib_path)\n",
    "    if status < 0:\n",
    "        raise ImportError(f'Error cargando: {lib_path}')\n",
    "\n",
    "print('Librerias cargadas. Listo!')",
]

CONFIG_SRC = [
    "# ================================================================\n",
    "# CONFIGURACIÓN CENTRAL — Editá solo esta celda\n",
    "# ================================================================\n",
    "\n",
    "# Directorio raíz donde están los ADST, organizados como:\n",
    "#   BASE_PATH / year / month / ADST_SUBSET_year_month_day.root\n",
    "BASE_PATH  = '/srv/workspace_favalli/ngonzalez/ADSTs/v4r2'\n",
    "\n",
    "# Años y meses a procesar\n",
    "YEARS  = [2021, 2022, 2023, 2024, 2025]\n",
    "MONTHS = ['01','02','03','04','05','06','07','08','09','10','11','12']\n",
    "\n",
    "# Subset (PhaseI, PhaseII, PhaseIISPMT, etc.)\n",
    "# Determina qué archivos buscar: ADST_PhaseI_YEAR_MONTH_DAY.root\n",
    "SUBSET = 'PhaseI'\n",
    "\n",
    "# Directorio de salida para los .parquet resultantes\n",
    "OUTPUT_DIR = './parquet_datos_campo/'\n",
    "\n",
    "# Número de workers en el Pool paralelo.\n",
    "# Regla práctica: empezar con 4, subir a 8-10 si el servidor aguanta.\n",
    "# Cada worker ocupa ~1-2 GB de RAM y un núcleo completo de CPU.\n",
    "# Con más de 10 workers la ganancia es marginal por limitaciones de I/O.\n",
    "N_WORKERS = 8\n",
    "\n",
    "# ── Cortes de calidad ────────────────────────────────────────────────\n",
    "# Se pasan a readADST_surface_data_v19 vía partial() en la celda de ejecución.\n",
    "# Podés modificarlos sin tocar la función de lectura.\n",
    "ONLY_6T5           = True   # Corte fiducial (recomendado: siempre True)\n",
    "MIN_LOG_E          = 17.0   # log10(E / eV) mínimo\n",
    "MAX_THETA_DEG      = 60.0   # Ángulo cenital máximo [grados]\n",
    "SKIP_REJECTED_STAS = True   # Saltear estaciones SD rechazadas\n",
    "\n",
    "os.makedirs(OUTPUT_DIR, exist_ok=True)\n",
    "print(f'Output dir:  {OUTPUT_DIR}')\n",
    "print(f'Cortes:      6T5={ONLY_6T5}, logE>={MIN_LOG_E}, theta<={MAX_THETA_DEG} deg')",
]

# La celda más importante: función con docstring exhaustivo
FUNCTIONS_SRC = [
    "# ===========================================================================\n",
    "# CELDA: FUNCIONES DE LECTURA — versión v19 (Datos Experimentales)\n",
    "# ===========================================================================\n",
    "\n",
    "def getModuleList(counter, sim=False):\n",
    "    \"\"\"\n",
    "    Devuelve los Módulos (segmentos de scintillador) de un Counter UMD.\n",
    "\n",
    "    DIFERENCIA CLAVE entre simulaciones y datos reales:\n",
    "    ─────────────────────────────────────────────────────\n",
    "    sim=True  (simulaciones, v17): IDs 0, 1, 2, 3, 4, 5\n",
    "      Los IDs en simulación son asignados secuencialmente por\n",
    "      el framework de Offline al crear el evento simulado.\n",
    "\n",
    "    sim=False (datos reales, v19): IDs 100, 101, ..., 115\n",
    "      Los IDs en datos reales corresponden al número físico\n",
    "      del segmento de hardware instalado en el campo (cada\n",
    "      counter UMD del SD-750 puede tener hasta 3 módulos).\n",
    "\n",
    "    Usamos HasModule() antes de GetModule() para no fallar si\n",
    "    un módulo está físicamente ausente o sin datos en ese evento.\n",
    "    \"\"\"\n",
    "    ids = range(0, 6) if sim else range(100, 116)\n",
    "    return [counter.GetModule(mid) for mid in ids if counter.HasModule(mid)]\n",
    "\n",
    "\n",
    "def readADST_surface_data_v19(\n",
    "    fname,\n",
    "    only_6T5=True,\n",
    "    min_logE=17.0,\n",
    "    max_theta_deg=60.0,\n",
    "    skip_rejected_stations=True,\n",
    "    verbose=False,\n",
    "):\n",
    "    \"\"\"\n",
    "    Lee un archivo ADST de DATOS EXPERIMENTALES del Observatorio Auger\n",
    "    y retorna un DataFrame con una fila por módulo UMD en eventos\n",
    "    que pasan todos los cortes de calidad.\n",
    "\n",
    "    ================================================================\n",
    "    HISTORIAL Y DIFERENCIAS RESPECTO A readADST_surface_v17\n",
    "    (la versión para simulaciones)\n",
    "    ================================================================\n",
    "\n",
    "    La v17 procesaba simulaciones CORSIKA/FLUKA donde la 'verdad'\n",
    "    completa (energía exacta, ángulos exactos, core exacto, muones\n",
    "    inyectados) estaba disponible vía MCShower y SimCounter.\n",
    "\n",
    "    La v19 procesa datos reales del Observatorio Auger (SD-750 + UMD)\n",
    "    donde NADA de eso existe. Todos los cambios se describen abajo,\n",
    "    con referencia al código C++ (ADSTReader.cc) que proporcionó\n",
    "    el director como referencia de los cortes estándar.\n",
    "\n",
    "    ----------------------------------------------------------------\n",
    "    CAMBIO 1 — Sin MCShower (la diferencia más fundamental)\n",
    "    ----------------------------------------------------------------\n",
    "    En v17 (simulaciones), al inicio de cada evento hacíamos:\n",
    "\n",
    "        MCShower = event.GetGenShower()\n",
    "        logE_MC  = np.log10(MCShower.GetEnergy())\n",
    "        theta_MC = MCShower.GetZenith() * 180.0 / np.pi\n",
    "        phi_MC   = MCShower.GetAzimuth() * 180.0 / np.pi\n",
    "        core_MC  = MCShower.GetCoreSiteCS()  # posición exacta del core\n",
    "        primary  = MCShower.GetShortPrimaryName()\n",
    "\n",
    "    En v19 (datos reales):\n",
    "      → GetGenShower() existe pero devuelve un objeto vacío/inválido.\n",
    "      → Llamarlo produce valores sin sentido o crashes silenciosos.\n",
    "      → Se ELIMINÓ toda mención a MCShower/GetGenShower.\n",
    "      → La energía, ángulos y core solo existen como RECONSTRUCCIÓN:\n",
    "\n",
    "        sShower  = sEvent.GetSdRecShower()\n",
    "        logE_REC = np.log10(sShower.GetEnergy())\n",
    "        theta    = sShower.GetZenith() * 180.0 / np.pi\n",
    "        phi      = sShower.GetAzimuth() * 180.0 / np.pi\n",
    "        core_REC = sShower.GetCoreSiteCS()\n",
    "\n",
    "    Esto también implica que variables como logE_MC, theta_MC,\n",
    "    phi_MC, primary, phi_plane_euler_MC, phi_plane_ground_mc, y\n",
    "    r_core_MC desaparecen completamente del DataFrame de salida.\n",
    "\n",
    "    ----------------------------------------------------------------\n",
    "    CAMBIO 2 — Sin SimCounter ni muones inyectados\n",
    "    ----------------------------------------------------------------\n",
    "    En v17 (simulaciones), la 'verdad' de muones del UMD se obtenía\n",
    "    con una estructura anidada compleja:\n",
    "\n",
    "        simCounter = mEvent.GetSimCounter(counterId)\n",
    "        # Bucle sobre canales del módulo:\n",
    "        while channelIterator != channelsEnd:\n",
    "            channel   = channelIterator.__deref__()\n",
    "            channelId = channel.GetId()\n",
    "            if simCounter.HasSimScintillatorByChannel(moduleId, channelId):\n",
    "                simScint = simCounter.GetSimScintillatorByChannelId(...)\n",
    "                nMuones_MC += simScint.GetNumberOfInjectedMuons()\n",
    "            channelIterator += 1\n",
    "\n",
    "    En v19 (datos reales):\n",
    "      → mEvent.GetSimCounter() retorna None siempre.\n",
    "      → No existen 'muones inyectados': la lluvia fue real, no simulada.\n",
    "      → Se eliminó GetSimCounter() y todo el bucle de canales.\n",
    "      → La ÚNICA señal de muones disponible es la reconstruida:\n",
    "\n",
    "        nMuones_REC = module.GetNumberOfEstimatedMuons()\n",
    "\n",
    "      Este número es el resultado del algoritmo de reconstrucción\n",
    "      del UMD que ajusta la forma del waveform para estimar cuántos\n",
    "      muones cruzaron el scintillador. No es una verdad, es una medida.\n",
    "\n",
    "    ----------------------------------------------------------------\n",
    "    CAMBIO 3 — Cortes de calidad (del C++ del director)\n",
    "    ----------------------------------------------------------------\n",
    "    El director proporcionó ADSTReader.cc + ADSTReader.h como\n",
    "    referencia de los cortes estándar del observatorio. Aquí se\n",
    "    replica cada corte en Python, con su equivalente C++ comentado.\n",
    "\n",
    "    [A] CORTE 6T5 — fiducial del arreglo (nivel de EVENTO)\n",
    "\n",
    "        Código C++ original (ADSTReader.cc, Run()):\n",
    "\n",
    "            if (!sdEvent.IsT5()) continue;\n",
    "            int nNeighUB  = sdEvent.GetT5PriorActiveNeighbors().size();\n",
    "            int nNeighUUB = sdEvent.GetT5PriorActiveUUBNeighbors().size();\n",
    "            if (nNeighUB < 5 && nNeighUUB < 5) continue;\n",
    "\n",
    "        Traducción Python (esta función):\n",
    "\n",
    "            if not sEvent.IsT5(): continue\n",
    "            n_ub  = sEvent.GetT5PriorActiveNeighbors().size()\n",
    "            n_uub = sEvent.GetT5PriorActiveUUBNeighbors().size()\n",
    "            if n_ub < 5 and n_uub < 5: continue\n",
    "\n",
    "        ¿Qué significa T5 y por qué es el corte más importante?\n",
    "\n",
    "        IsT5() verifica que la estación más activa de la lluvia\n",
    "        ('hottest station') tenía sus 6 vecinos inmediatos activos\n",
    "        en el momento del trigger. Garantiza que el core de la\n",
    "        lluvia cayó DENTRO del arreglo activo.\n",
    "\n",
    "        Sin T5, el core puede haber caído fuera del arreglo y la\n",
    "        reconstrucción de energía, ángulo y core pueden ser muy\n",
    "        malas. En simulaciones, el arreglo es ideal y este corte\n",
    "        no es tan crítico. En datos reales, hay sectores del arreglo\n",
    "        offline por mantenimiento o fallas, haciendo este corte\n",
    "        imprescindible.\n",
    "\n",
    "        UB  = Upgrade Board (electrónica vieja, Phase I)\n",
    "        UUB = Upgraded Upgrade Board (electrónica nueva, Phase II)\n",
    "        El OR entre ambos (nNeighUB>=5 OR nNeighUUB>=5) cubre el\n",
    "        período de transición 2021-presente donde ambas coexisten.\n",
    "\n",
    "        NOTA: en los datos de v4r2, muchos archivos ya vienen con\n",
    "        pre-selección T5 aplicada en la producción, por eso el corte\n",
    "        no tira eventos adicionales. Pero conviene dejarlo activo\n",
    "        como seguro para datasets donde esto no sea el caso.\n",
    "\n",
    "    [B] CORTE DE ENERGÍA (nivel de EVENTO)\n",
    "\n",
    "        C++: if (logE < minLgE) continue;  (ADSTReader.cc, Run())\n",
    "        Python: if logE < min_logE: continue\n",
    "\n",
    "        Por defecto min_logE=17.0 (10^17 eV).\n",
    "        El SD-750 alcanza 100% de eficiencia de trigger alrededor\n",
    "        de ese umbral. Bajo ese valor hay sesgos de trigger que\n",
    "        complican cualquier análisis estadístico.\n",
    "\n",
    "    [C] CORTE DE ÁNGULO CENITAL (nivel de EVENTO)\n",
    "\n",
    "        No está en el C++ del director pero es estándar en Auger.\n",
    "        Por defecto max_theta_deg=60.0 grados.\n",
    "\n",
    "        ¿Por qué 60°?\n",
    "        Para theta > 60°, la lluvia es muy inclinada. El muón llega\n",
    "        al UMD con una trayectoria más oblicua, recorriendo más\n",
    "        camino en el scintillador. La respuesta del detector cambia\n",
    "        y la reconstrucción de nMuones es menos confiable.\n",
    "        La mayoría de análisis de composición usan 0-60°.\n",
    "\n",
    "    [D] ESTACIONES SD RECHAZADAS (nivel de ESTACIÓN)\n",
    "\n",
    "        C++: en ADSTReader.h (struct StationFlags) y Run()\n",
    "        Python: if sdStation.IsRejected(): continue\n",
    "\n",
    "        Causas frecuentes de rechazo en datos reales:\n",
    "          lightning  : el tank fue golpeado por un rayo (señal espuria)\n",
    "          noCalib    : sin constante de calibración VEM válida\n",
    "          badSilent  : no respondió al trigger pero no hay razón conocida\n",
    "          offGrid    : antena GPS/comunicaciones caída\n",
    "          notAliveT2 : no respondió al trigger local T2\n",
    "          lowGainSat : saturación del canal de baja ganancia\n",
    "\n",
    "        En simulaciones este rechazo es raro (<1%).\n",
    "        En datos reales es normal ver 5-15% de estaciones rechazadas.\n",
    "\n",
    "    [E] COUNTERS UMD RECHAZADOS (nivel de COUNTER)\n",
    "\n",
    "        Python: if counter.IsRejected(): continue\n",
    "\n",
    "        El UMD tiene su propio sistema de calidad independiente del SD.\n",
    "        Un counter puede ser rechazado por problemas en la electrónica\n",
    "        del UMD (EASIER board) sin que el WCD asociado tenga problemas.\n",
    "\n",
    "    ----------------------------------------------------------------\n",
    "    CAMBIO 4 — Geometría simplificada (sin DetectorGeometry)\n",
    "    ----------------------------------------------------------------\n",
    "    En v17 (simulaciones), cargábamos la geometría del detector y\n",
    "    calculábamos manualmente la posición en el plano de lluvia:\n",
    "\n",
    "        geo = ROOT.DetectorGeometry()               # objeto costoso\n",
    "        file1.ReadDetectorGeometry(geo)             # lectura lenta\n",
    "        pos_station = geo.GetStationPosition(sdId)  # por estación\n",
    "        dx = pos_station.X() - core_MC.X()\n",
    "        dy = pos_station.Y() - core_MC.Y()\n",
    "        # ... rotaciones 3D con TVector3 para phi_euler ...\n",
    "\n",
    "    En v19 (datos reales):\n",
    "      → NO se usa DetectorGeometry. Mejora la velocidad ~2x.\n",
    "      → El framework de Offline ya calculó estas distancias al\n",
    "        reconstruir el evento. Se acceden directamente:\n",
    "\n",
    "        r_core      = sdStation.GetSPDistance()    # distancia al core [m]\n",
    "        phi_plane   = sdStation.GetAzimuthSP()     # azimuth relativo [rad]\n",
    "\n",
    "      → SP = Shower Plane (plano de lluvia). Las coordenadas ya están\n",
    "        en el sistema de referencia del eje de la lluvia.\n",
    "\n",
    "      → ATENCIÓN: phi_plane_sp devuelve valores en [-pi, pi],\n",
    "        NO en [0, 2pi]. Para normalizar en el análisis posterior:\n",
    "            phi_normalizado = phi_plane_sp % (2 * np.pi)\n",
    "\n",
    "    ----------------------------------------------------------------\n",
    "    CAMBIO 5 — verbose=False para no saturar Jupyter en paralelo\n",
    "    ----------------------------------------------------------------\n",
    "    La v17 imprimía progreso cada 500 eventos:\n",
    "        print(f'... procesados {event_count} eventos.')\n",
    "\n",
    "    Con 8 workers corriendo simultáneamente, esto genera cientos de\n",
    "    líneas mezcladas por segundo y puede disparar el error:\n",
    "        'IOPub data rate exceeded'\n",
    "    (el mismo que aparece en los outputs del notebook de simulaciones).\n",
    "\n",
    "    Con verbose=False (default), la función no imprime nada.\n",
    "    El wrapper process_file_wrapper_data maneja el log de progreso\n",
    "    a nivel de archivo (un mensaje por archivo, no por evento).\n",
    "\n",
    "    ----------------------------------------------------------------\n",
    "    Parameters\n",
    "    ----------------------------------------------------------------\n",
    "    fname : str\n",
    "        Ruta al archivo .root. Ej: ADST_PhaseI_2021_04_03.root\n",
    "    only_6T5 : bool\n",
    "        Aplicar el corte fiducial 6T5. Siempre True en producción.\n",
    "    min_logE : float\n",
    "        log10(E/eV) mínimo aceptado. Default 17.0.\n",
    "    max_theta_deg : float\n",
    "        Ángulo cenital máximo [grados]. Default 60.0.\n",
    "    skip_rejected_stations : bool\n",
    "        Saltear estaciones SD marcadas como rechazadas. Default True.\n",
    "    verbose : bool\n",
    "        Imprimir resumen al final. Default False (para Pool paralelo).\n",
    "\n",
    "    Returns\n",
    "    -------\n",
    "    pd.DataFrame\n",
    "        Una fila por módulo UMD que pasó todos los cortes.\n",
    "        Columnas: event_id, logE_REC, theta_REC, phi_REC, core_x, core_y,\n",
    "        counterId, sdId, moduleId, nMuones_REC, module_status,\n",
    "        r_core, r_core_err, phi_plane_sp,\n",
    "        is_sd_saturated, sdSignal_REC, sdSignal_err, sdMuonSignal_REC.\n",
    "        (El wrapper agrega: subset, year, month, day.)\n",
    "    \"\"\"\n",
    "    if not os.path.exists(fname):\n",
    "        return pd.DataFrame()\n",
    "\n",
    "    # ── Inicialización de ROOT ─────────────────────────────────────────\n",
    "    # DIFERENCIA con v17: en v17 también creábamos DetectorGeometry aquí.\n",
    "    # En v19 no lo necesitamos: el SDEvent ya tiene la geometría calculada.\n",
    "    # Esto elimina la llamada a ReadDetectorGeometry() que era costosa.\n",
    "    files = ROOT.std.vector('string')()\n",
    "    files.push_back(fname)\n",
    "    file1 = ROOT.RecEventFile(files)\n",
    "    event = ROOT.RecEvent()\n",
    "    file1.SetBuffers(event)\n",
    "\n",
    "    data = []\n",
    "    n_read = n_no_energy = n_no_t5 = n_theta_cut = n_passed = 0\n",
    "    t0 = time.time()\n",
    "\n",
    "    # ── BUCLE PRINCIPAL DE EVENTOS ─────────────────────────────────────\n",
    "    while file1.ReadNextEvent() == ROOT.RecEventFile.eSuccess:\n",
    "        n_read += 1\n",
    "\n",
    "        # SDEvent: contiene la reconstrucción del detector de superficie.\n",
    "        # DIFERENCIA v17: en v17 también accedíamos a event.GetGenShower()\n",
    "        # para la verdad MC. En v19 NO lo hacemos: devuelve datos inválidos.\n",
    "        sEvent  = event.GetSDEvent()\n",
    "        sShower = sEvent.GetSdRecShower()\n",
    "\n",
    "        # ── CORTE A: ENERGÍA ───────────────────────────────────────────\n",
    "        # C++: if (logE < minLgE) continue;\n",
    "        rec_energy = sShower.GetEnergy()\n",
    "        if rec_energy <= 0:\n",
    "            n_no_energy += 1\n",
    "            continue\n",
    "        logE = np.log10(rec_energy)\n",
    "        if logE < min_logE:\n",
    "            n_no_energy += 1\n",
    "            continue\n",
    "\n",
    "        # ── CORTE B: 6T5 FIDUCIAL ──────────────────────────────────────\n",
    "        # Traducción exacta del C++ del director (ADSTReader.cc):\n",
    "        #   if (!sdEvent.IsT5()) continue;\n",
    "        #   if (nNeighUB < 5 && nNeighUUB < 5) continue;\n",
    "        if only_6T5:\n",
    "            if not sEvent.IsT5():\n",
    "                n_no_t5 += 1\n",
    "                continue\n",
    "            n_ub  = sEvent.GetT5PriorActiveNeighbors().size()\n",
    "            n_uub = sEvent.GetT5PriorActiveUUBNeighbors().size()\n",
    "            if n_ub < 5 and n_uub < 5:\n",
    "                n_no_t5 += 1\n",
    "                continue\n",
    "\n",
    "        # ── CORTE C: ÁNGULO CENITAL ────────────────────────────────────\n",
    "        theta = sShower.GetZenith() * 180.0 / np.pi\n",
    "        if theta > max_theta_deg:\n",
    "            n_theta_cut += 1\n",
    "            continue\n",
    "\n",
    "        n_passed += 1\n",
    "\n",
    "        # ── Variables del evento que pasó los cortes ───────────────────\n",
    "        # DIFERENCIA v17: en v17 aquí también extraíamos logE_MC,\n",
    "        # theta_MC, phi_MC, core_MC, primary de MCShower.\n",
    "        # En v19 solo existe la reconstrucción.\n",
    "        ev_id          = event.GetEventId()\n",
    "        phi            = sShower.GetAzimuth() * 180.0 / np.pi\n",
    "        pos_core       = sShower.GetCoreSiteCS()\n",
    "        core_x, core_y = pos_core.X(), pos_core.Y()\n",
    "\n",
    "        # ── BUCLE SOBRE COUNTERS (estaciones UMD) ─────────────────────\n",
    "        mEvent   = event.GetMDEvent()\n",
    "        it, end  = mEvent.CountersBegin(), mEvent.CountersEnd()\n",
    "\n",
    "        while it != end:\n",
    "            c    = it.__deref__()\n",
    "            cid  = c.GetId()\n",
    "            # sdPartnerId: ID de la estación WCD (SD) asociada a este UMD.\n",
    "            # Con esto 'linkeamos' el MDEvent con el SDEvent.\n",
    "            sdId = c.GetSdPartnerId()\n",
    "\n",
    "            # Si la estación SD no participó en la reconstrucción de\n",
    "            # este evento, no tiene sentido incluirla.\n",
    "            if not sEvent.HasStation(sdId):\n",
    "                it += 1\n",
    "                continue\n",
    "            st = sEvent.GetStationById(sdId)\n",
    "\n",
    "            # ── CORTE D: ESTACIÓN SD RECHAZADA ─────────────────────────\n",
    "            # C++: struct StationFlags en ADSTReader.h\n",
    "            # Causas: lightning, noCalib, badSilent, offGrid, ...\n",
    "            if skip_rejected_stations and st.IsRejected():\n",
    "                it += 1\n",
    "                continue\n",
    "\n",
    "            # ── CORTE E: COUNTER UMD RECHAZADO ─────────────────────────\n",
    "            if c.IsRejected():\n",
    "                it += 1\n",
    "                continue\n",
    "\n",
    "            # ── Geometría en el plano de lluvia ─────────────────────────\n",
    "            # DIFERENCIA v17: en v17 calculábamos r y phi manualmente\n",
    "            # con geo.GetStationPosition() y rotaciones TVector3.\n",
    "            # En v19 usamos directamente los valores del SDEvent.\n",
    "            # RECORDAR: phi_plane_sp está en [-pi, pi], no en [0, 2pi].\n",
    "            r_core       = st.GetSPDistance()\n",
    "            r_core_err   = st.GetSPDistanceError()\n",
    "            phi_plane_sp = st.GetAzimuthSP()\n",
    "\n",
    "            # ── Señales del WCD (SD) ─────────────────────────────────────\n",
    "            is_sat        = st.IsLowGainSaturated()\n",
    "            sd_signal     = st.GetTotalSignal()       # [VEM]\n",
    "            sd_signal_err = st.GetTotalSignalError()  # [VEM]\n",
    "            sd_muon_sig   = st.GetMuonSignal()        # [VEM] suele ser 0\n",
    "\n",
    "            # ── BUCLE SOBRE MÓDULOS UMD ──────────────────────────────────\n",
    "            # DIFERENCIA v17: sim=True usaba IDs 0-5 (simulación).\n",
    "            # En v19: sim=False usa IDs 100-115 (hardware real).\n",
    "            for m in getModuleList(c, sim=False):\n",
    "\n",
    "                # Señal reconstruida del módulo.\n",
    "                # DIFERENCIA v17: en v17 también teníamos nMuones_MC\n",
    "                # (verdad de la simulación via GetNumberOfInjectedMuons).\n",
    "                # En v19 nMuones_REC es la ÚNICA medida de muones disponible.\n",
    "                nMuones_REC = m.GetNumberOfEstimatedMuons()\n",
    "                moduleId    = m.GetId()\n",
    "\n",
    "                # Estado del módulo (flag de calidad de la reconstrucción UMD)\n",
    "                # candidate: módulo usado activamente en la reconstrucción\n",
    "                # saturated: señal alta, reconstrucción con incerteza mayor\n",
    "                # rejected:  excluido por el control de calidad del UMD\n",
    "                # silent:    sin señal (puede ser normal a grandes distancias)\n",
    "                # undefined: estado no reconocido (no debería ocurrir)\n",
    "                if   m.IsCandidate(): s = 'candidate'\n",
    "                elif m.IsSaturated(): s = 'saturated'\n",
    "                elif m.IsRejected():  s = 'rejected'\n",
    "                elif m.IsSilent():    s = 'silent'\n",
    "                else:                 s = 'undefined'\n",
    "\n",
    "                data.append({\n",
    "                    'event_id':         ev_id,\n",
    "                    # Lluvia (solo reconstrucción; no hay verdad MC)\n",
    "                    'logE_REC':         logE,\n",
    "                    'theta_REC':        theta,\n",
    "                    'phi_REC':          phi,\n",
    "                    'core_x':           core_x,\n",
    "                    'core_y':           core_y,\n",
    "                    # Identidad del módulo\n",
    "                    'counterId':        cid,\n",
    "                    'sdId':             sdId,\n",
    "                    'moduleId':         moduleId,\n",
    "                    # Señal UMD\n",
    "                    'nMuones_REC':      nMuones_REC,\n",
    "                    'module_status':    s,\n",
    "                    # Geometría (plano de lluvia, calculada por Offline)\n",
    "                    'r_core':           r_core,\n",
    "                    'r_core_err':       r_core_err,\n",
    "                    'phi_plane_sp':     phi_plane_sp,  # en [-pi, pi]\n",
    "                    # Señal del WCD (SD) asociado\n",
    "                    'is_sd_saturated':  is_sat,\n",
    "                    'sdSignal_REC':     sd_signal,\n",
    "                    'sdSignal_err':     sd_signal_err,\n",
    "                    'sdMuonSignal_REC': sd_muon_sig,\n",
    "                })\n",
    "\n",
    "            it += 1\n",
    "\n",
    "    # ── Resumen opcional ──────────────────────────────────────────────\n",
    "    if verbose:\n",
    "        elapsed = time.time() - t0\n",
    "        fn = os.path.basename(fname)\n",
    "        print(f'  [{fn}]')\n",
    "        print(f'    Leidos={n_read} | Pasaron={n_passed} | Filas={len(data)}')\n",
    "        print(f'    Tirados: E={n_no_energy} T5={n_no_t5} theta={n_theta_cut}')\n",
    "        print(f'    Tiempo: {elapsed:.1f}s')\n",
    "\n",
    "    return pd.DataFrame(data)",
]

WRAPPER_SRC = [
    "def process_file_wrapper_data(\n",
    "    root_fpath,\n",
    "    output_dir,\n",
    "    only_6T5=True,\n",
    "    min_logE=17.0,\n",
    "    max_theta_deg=60.0,\n",
    "    skip_rejected_stations=True,\n",
    "):\n",
    "    \"\"\"\n",
    "    Función trabajadora para el Pool paralelo.\n",
    "\n",
    "    Adaptada de process_file_wrapper (simulaciones) para el formato\n",
    "    de nombre de archivos de datos reales:\n",
    "        ADST_PhaseI_2021_04_03.root  →  ADST_PhaseI_2021_04_03.parquet\n",
    "\n",
    "    Diferencias con la versión de simulaciones:\n",
    "    - En sim: parseábamos modelo/energía/primario del nombre del archivo.\n",
    "    - En datos reales: parseamos subset/year/month/day.\n",
    "    - verbose=False para no saturar el buffer de salida de Jupyter\n",
    "      cuando 8-10 workers imprimen simultáneamente.\n",
    "    - Resume automático: si el .parquet ya existe, se saltea.\n",
    "    \"\"\"\n",
    "    filename       = os.path.basename(root_fpath)\n",
    "    output_fname   = filename.replace('.root', '.parquet')\n",
    "    output_path    = os.path.join(output_dir, output_fname)\n",
    "\n",
    "    # ── Resume automático ─────────────────────────────────────────────\n",
    "    # Si el .parquet ya existe (de una corrida anterior interrumpida),\n",
    "    # lo saltamos. Esto permite retomar el procesamiento sin empezar\n",
    "    # de cero. Mismo comportamiento que la versión de simulaciones.\n",
    "    if os.path.exists(output_path):\n",
    "        return f'INFO: Ya existe, saltando: {output_fname}'\n",
    "\n",
    "    print(f'► [Iniciando]: {filename}')\n",
    "\n",
    "    try:\n",
    "        t0 = time.time()\n",
    "\n",
    "        # verbose=False: sin prints por evento.\n",
    "        # El resumen de estadísticas se descarta en paralelo para\n",
    "        # no saturar el IOPub buffer de Jupyter (el mismo warning\n",
    "        # que aparecía en el notebook de simulaciones).\n",
    "        df = readADST_surface_data_v19(\n",
    "            root_fpath,\n",
    "            only_6T5=only_6T5,\n",
    "            min_logE=min_logE,\n",
    "            max_theta_deg=max_theta_deg,\n",
    "            skip_rejected_stations=skip_rejected_stations,\n",
    "            verbose=False,\n",
    "        )\n",
    "\n",
    "        if df.empty:\n",
    "            return f'INFO: Sin datos tras los cortes: {filename}'\n",
    "\n",
    "        # ── Parsear metadatos del nombre del archivo ───────────────────\n",
    "        # Formato: ADST_PhaseI_2021_04_03.root\n",
    "        # partes:  [0]='ADST' [1]='PhaseI' [2]='2021' [3]='04' [4]='03'\n",
    "        try:\n",
    "            parts        = filename.replace('.root', '').split('_')\n",
    "            df['subset'] = parts[1]       # 'PhaseI', 'PhaseII', etc.\n",
    "            df['year']   = int(parts[2])  # 2021\n",
    "            df['month']  = int(parts[3])  # 4\n",
    "            df['day']    = int(parts[4])  # 3\n",
    "        except Exception as e_parse:\n",
    "            print(f'  Advertencia: no se pudo parsear {filename}: {e_parse}')\n",
    "\n",
    "        # ── Guardar en Parquet ─────────────────────────────────────────\n",
    "        # snappy: buena relación velocidad/compresión para DataFrames\n",
    "        # densos de floats. Compatible con pandas.read_parquet().\n",
    "        df.to_parquet(output_path, compression='snappy', index=False)\n",
    "\n",
    "        # ── Liberar memoria explícitamente ─────────────────────────────\n",
    "        # Importante en Pool: cada worker vive hasta que el Pool cierra,\n",
    "        # así que sin gc.collect() la RAM puede crecer mucho.\n",
    "        del df\n",
    "        gc.collect()\n",
    "\n",
    "        elapsed = time.time() - t0\n",
    "        return f'✔ [Exito]: {filename} → {output_fname} ({elapsed:.1f}s)'\n",
    "\n",
    "    except Exception:\n",
    "        return f'❌ [ERROR] en {filename}:\\n{traceback.format_exc()}'",
]

FILES_SRC = [
    "# ── Construir la lista de todos los archivos a procesar ────────────────\n",
    "print(f'Buscando archivos: ADST_{SUBSET}_YEAR_MONTH_*.root')\n",
    "print(f'Directorio base:   {BASE_PATH}')\n",
    "print()\n",
    "\n",
    "all_files = []\n",
    "for year in YEARS:\n",
    "    for month in MONTHS:\n",
    "        pattern = os.path.join(\n",
    "            BASE_PATH, str(year), month,\n",
    "            f'ADST_{SUBSET}_{year}_{month}_*.root'\n",
    "        )\n",
    "        day_files = sorted(glob.glob(pattern))\n",
    "        all_files.extend(day_files)\n",
    "        if day_files:\n",
    "            print(f'  {year}/{month}: {len(day_files):>2} dias')\n",
    "\n",
    "print()\n",
    "print(f'Total de archivos encontrados: {len(all_files)}')\n",
    "\n",
    "# ── Chequear cuáles ya están procesados (resume) ──────────────────────\n",
    "ya_listos = [\n",
    "    f for f in all_files\n",
    "    if os.path.exists(\n",
    "        os.path.join(OUTPUT_DIR, os.path.basename(f).replace('.root', '.parquet'))\n",
    "    )\n",
    "]\n",
    "pendientes = len(all_files) - len(ya_listos)\n",
    "print(f'Ya procesados (se saltearán): {len(ya_listos)}')\n",
    "print(f'Pendientes de procesar:       {pendientes}')",
]

RUN_SRC = [
    "if not all_files:\n",
    "    print('ERROR: No se encontraron archivos. Revisá BASE_PATH y SUBSET.')\n",
    "\n",
    "elif pendientes == 0:\n",
    "    print('Todos los archivos ya están procesados. Nada que hacer.')\n",
    "\n",
    "else:\n",
    "    print(f'--- INICIANDO PROCESO PARALELO ({N_WORKERS} workers) ---')\n",
    "    print(f'Archivos pendientes: {pendientes}')\n",
    "    print(f'Cortes: 6T5={ONLY_6T5}, logE>={MIN_LOG_E}, theta<={MAX_THETA_DEG}')\n",
    "    print()\n",
    "\n",
    "    t_total = time.time()\n",
    "\n",
    "    # ── Función parcial con parámetros congelados ─────────────────────\n",
    "    # partial() 'congela' los argumentos fijos (output_dir, cortes),\n",
    "    # dejando solo root_fpath variable. Así pool.map() puede distribuir\n",
    "    # la lista de archivos sin necesidad de tuplas ni estructuras extra.\n",
    "    # Mismo patrón que en la versión de simulaciones (v17/v8).\n",
    "    process_func = partial(\n",
    "        process_file_wrapper_data,\n",
    "        output_dir          = OUTPUT_DIR,\n",
    "        only_6T5            = ONLY_6T5,\n",
    "        min_logE            = MIN_LOG_E,\n",
    "        max_theta_deg       = MAX_THETA_DEG,\n",
    "        skip_rejected_stations = SKIP_REJECTED_STAS,\n",
    "    )\n",
    "\n",
    "    # ── Ejecución paralela ────────────────────────────────────────────\n",
    "    # Pool crea N_WORKERS procesos Python independientes.\n",
    "    # pool.map() distribuye all_files entre ellos y espera a que\n",
    "    # todos terminen antes de retornar la lista de resultados.\n",
    "    # Cada worker carga sus propias librerías de ROOT y Offline:\n",
    "    # por eso es IMPRESCINDIBLE que el entorno Auger esté cargado\n",
    "    # antes de abrir Jupyter (la celda de setup lo verifica).\n",
    "    with Pool(processes=N_WORKERS) as pool:\n",
    "        results = pool.map(process_func, all_files)\n",
    "\n",
    "    print('\\n--- Proceso Paralelo Completado ---\\n')\n",
    "\n",
    "    # ── Resultados ────────────────────────────────────────────────────\n",
    "    exitos  = 0\n",
    "    errores = 0\n",
    "    skipped = 0\n",
    "\n",
    "    for res in results:\n",
    "        print(res)\n",
    "        if '✔ [Exito]'  in res: exitos  += 1\n",
    "        elif '❌ [ERROR]' in res: errores += 1\n",
    "        elif 'INFO'       in res: skipped += 1\n",
    "\n",
    "    elapsed_min = (time.time() - t_total) / 60\n",
    "    print(f'\\n--- Resumen ---')\n",
    "    print(f'Tiempo total:        {elapsed_min:.2f} minutos')\n",
    "    print(f'Archivos procesados: {exitos}')\n",
    "    print(f'Ya existían:         {skipped}')\n",
    "    print(f'Con errores:         {errores}')\n",
    "    print(f'Parquets en:         {OUTPUT_DIR}')",
]

# =============================================================================
# CONSTRUIR EL NOTEBOOK
# =============================================================================

cells = [
    mc("m_title", [
        "# Procesamiento Paralelo — Datos Experimentales Auger SD-750 + UMD\n",
        "\n",
        "Procesa todos los archivos ADST de datos reales y los guarda como `.parquet`.  \n",
        "Adaptado del pipeline de simulaciones `v17/v8` con los cambios necesarios  \n",
        "para datos experimentales (sin MC truth, cortes de calidad estrictos).\n",
        "\n",
        "**Workflow:**\n",
        "1. Setup del entorno Auger Offline\n",
        "2. Configuración central (paths, años, cortes)\n",
        "3. Funciones de lectura (v19) — documentadas exhaustivamente\n",
        "4. Función trabajadora (`process_file_wrapper_data`)\n",
        "5. Búsqueda de archivos + resume automático\n",
        "6. Ejecución con `Pool(N_WORKERS)`",
    ]),
    cc("c_imports", IMPORTS_SRC),
    cc("c_auger",   AUGER_SRC),
    mc("m_config", [
        "## ⚙️ Configuración central\n",
        "\n",
        "**Editá solo esta celda** para cambiar qué datos procesar y con qué cortes."
    ]),
    cc("c_config",    CONFIG_SRC),
    mc("m_functions", [
        "## 📦 Funciones de lectura — v19\n",
        "\n",
        "La función `readADST_surface_data_v19` está comentada exhaustivamente,  \n",
        "explicando cada diferencia con la versión de simulaciones (`v17`)  \n",
        "y el origen de cada corte de calidad (C++ del director, `ADSTReader.cc`)."
    ]),
    cc("c_functions", FUNCTIONS_SRC),
    mc("m_wrapper", [
        "## 🔧 Función trabajadora\n",
        "\n",
        "Misma arquitectura que `process_file_wrapper` de simulaciones:  \n",
        "recibe un path, llama a la función de lectura, guarda el `.parquet`,  \n",
        "retorna un string de resultado (`✔`, `❌`, o `INFO`)."
    ]),
    cc("c_wrapper", WRAPPER_SRC),
    mc("m_files", [
        "## 📂 Búsqueda de archivos\n",
        "\n",
        "Construye la lista de todos los `.root` a procesar  \n",
        "e indica cuántos ya tienen su `.parquet` (resume automático)."
    ]),
    cc("c_files", FILES_SRC),
    mc("m_run", [
        "## 🚀 Ejecución paralela\n",
        "\n",
        "Mismo patrón que en simulaciones: `partial()` + `Pool.map()`.  \n",
        "Si un archivo ya tiene su `.parquet`, se saltea automáticamente.  \n",
        "Podés interrumpir y retomar sin perder trabajo."
    ]),
    cc("c_run", RUN_SRC),
]

notebook = {
    "cells": cells,
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3 (ipykernel)",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {"name": "ipython", "version": 3},
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "pygments_lexer": "ipython3",
            "version": "3.12.3"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 5
}

out = 'Procesamiento_Datos_Campo_v1.ipynb'
with open(out, 'w', encoding='utf-8') as f:
    json.dump(notebook, f, indent=1, ensure_ascii=False)
print(f'Notebook generado: {out}')
